### ISSUE TITLE
<header>が衝突する

### ISSUE THREAD

**Issue by inutano** [dbcls/website#3]
`<header>` タグを挿入して、そこにスタイルを当てるという方法が取られていますが、既にアプリケーション側に `<header>` というタグが利用されている場合に namespace が衝突するのがよろしくないです。別のユニークなタグ名に変更するか、`<div id="dbcls-common-header">` のようなユニークなDOM名をアサインする方がよいです (さもなくばアプリ側でそこそこしんどい修正が必要になる)

**Comment by inutano** [comment]
すみません、共通ヘッダフッタの話です。

**Comment by hiromasaono** [comment]
Fixしましたので、表示がバグらないか検証していただきたく!
https://github.com/dbcls/website/tree/master/DBCLS-common-header-footer

**Comment by dogrunjp** [comment]
DDBJ Searchでの表示を確認しました。

**Comment by dogrunjp** [comment]
ライセンス部分の質問＆要望なのですが、DDBJ Searchのライセンスは[INSDC Policy](http://www.insdc.org/policy.html) にして欲しいと児玉さんから言われていたのを思い出しました。ライセンスは現在CC-BY-2.1-JP、CC-BY-SA-2.1-JP、表示無しの3種類ありますが、ここにPolicyを追加することはできるでしょうか？あるいは表示無しを選択してライセンスだけ別に表示する対応の方が良いでしょうか？

**Comment by hiromasaono** [comment]
@dogrunjp 表示確認ありがとうございます。一方で、DDBJ Search のライセンスはINSDC Policyにしたいということであれば、テンプレ追加よりも個別対応(ライセンス表示無し+INSDC付記 or 独自フッタ作成)のほうが良いのかなと思いますが、どうでしょうか。 @inutano

**Comment by inutano** [comment]
DDBJの方で fork してもらってそこで独自の修正を加えてもらうのがいいんじゃないですかね。その意味でもヘッダフッタはwebsiteからはレポジトリ分けた方がよさそうです。

**Comment by inutano** [comment]
website と同じレポジトリに入ってる強い理由はとくにないですよね？

**Comment by dogrunjp** [comment]
DDBJのフッタは独自対応が良さそうですね。

**Comment by hiromasaono** [comment]
@dogrunjp ヘッダ・フッタのソースの置き場所を変える方向で作業しますが、とりいそぎDDBJ searchは独自対応ということでおねがいします。
