### ISSUE TITLE
共通ヘッダ・フッタ導入方法改善提案

### ISSUE THREAD

**Issue by inutano** [dbcls/website#4]
共通ヘッダ・フッタの導入のため、現状では

- `<link>` で CSS の読み込み
- `<script>` で javascript の読み込み
- `<meta>` 挿入でモバイル対応
- `<body>` の attr 書き換え
- `<header>` タグの挿入

の作業が必要です。が、全てjavascriptで自動的にできるものかと思います。

上の手順を全てjavascriptの中に書いてしまって、 `<script>` を読み込むだけでOKとしてしまうのがよいかとおもいますがいかがでしょうか。

**Comment by hiromasaono** [comment]
<script> を読み込むだけでOKになりました。
https://github.com/dbcls/website/tree/master/DBCLS-common-header-footer

**Comment by inutano** [comment]
![great-gatsby-thank-you-memes](https://user-images.githubusercontent.com/221804/44695014-ddac8280-aaab-11e8-9fc1-4f4aa089cd84.jpg)
